version: "3"

services:
  redis:
    container_name: soq_redis
    image: redis:4.0-alpine
    expose:
      - "6379"

  web:
    container_name: soq_web
    build:
      context: ./web
    image: soq/web:0.0.2
    depends_on:
      - redis
    ports:
      - "10086:5000"
    volumes:
      - soq-attachment-volume:/attachments

volumes:
     soq-attachment-volume: 
