version: "3"

services:
  redis:
    container_name: soq_redis
    image: redis:4.0-alpine
    expose:
      - "6379"

  web:
    container_name: soq_web
    build:
      context: ./web
    image: soq/web:0.1.5
    depends_on:
      - redis
    ports:
      - "10086:5000"
    volumes:
      - soq-attachment-volume:/attachments

  core:
    container_name: soq_core
    build:
      context: ./corenlp
    image: soq/core:0.1.6
    expose:
      - "9000"

  processor:
    container_name: soq_processor
    build:
      context: ./processor
    image: soq/processor:0.1.7
    depends_on:
      - redis
      - core

volumes:
     soq-attachment-volume: 
