tagged_sentences = [[('b', 'O', 'NN'), ('"', 'O', '``'), ('Image', 'O', 'NN'), ('copyrightGetty', 'O', 'NN'),
                     ('ImagesSainsbury', 'O', 'NNP'), ("'s", 'O', 'POS'), ('has', 'O', 'VBZ'),
                     ('confirmed', 'O', 'VBN'), ('plans', 'O', 'NNS'), ('to', 'O', 'TO'), ('merge', 'O', 'VB'),
                     ('with', 'O', 'IN'), ('Asda', 'ORGANIZATION', 'NNP'), (',', 'O', ','), ('which', 'O', 'WDT'),
                     ('is', 'O', 'VBZ'), ('currently', 'DATE', 'RB'), ('owned', 'O', 'VBN'), ('by', 'O', 'IN'),
                     ('US', 'COUNTRY', 'NNP'), ('supermarket', 'O', 'NN'), ('giant', 'O', 'NN'),
                     ('Walmart', 'ORGANIZATION', 'NNP'), ('.', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Sainsbury', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'),
                     ('chief', 'TITLE', 'JJ'), ('executive', 'TITLE', 'NN'), ('Mike', 'PERSON', 'NNP'),
                     ('Coupe', 'PERSON', 'NNP'), ('also', 'O', 'RB'), ('said', 'O', 'VBD'), ('the', 'O', 'DT'),
                     ('deal', 'O', 'NN'), ('would', 'O', 'MD'), ('not', 'O', 'RB'), ('lead', 'O', 'VB'),
                     ('to', 'O', 'TO'), ('store', 'O', 'VB'), ('closures', 'O', 'NNS'), ('or', 'O', 'CC'),
                     ('job', 'O', 'NN'), ('losses', 'O', 'NNS'), ('in', 'O', 'IN'), ('stores', 'O', 'NNS'),
                     ('.', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('The', 'O', 'DT'), ('combination', 'O', 'NN'),
                     ('of', 'O', 'IN'), ('the', 'O', 'DT'), ('UK', 'COUNTRY', 'NNP'), ("'s", 'O', 'POS'),
                     ('second', 'ORDINAL', 'JJ'), ('and', 'ORDINAL', 'CC'), ('third', 'ORDINAL', 'JJ'),
                     ('largest', 'O', 'JJS'), ('supermarkets', 'O', 'NNS'), ('would', 'O', 'MD'), ('create', 'O', 'VB'),
                     ('a', 'O', 'DT'), ('giant', 'O', 'NN'), (',', 'O', ','), ('representing', 'O', 'VBG'),
                     ('nearly', 'O', 'RB'), ('1', 'NUMBER', 'CD'), ('in', 'O', 'IN'), ('every', 'O', 'DT'),
                     ('3', 'NUMBER', 'CD'), ('spent', 'O', 'VBN'), ('on', 'O', 'IN'), ('groceries', 'O', 'NNS'),
                     ('.', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Mr', 'O', 'NNP'), ('Coupe', 'O', 'NNP'), ('-', 'O', ':'),
                     ('who', 'O', 'WP'), ('will', 'O', 'MD'), ('lead', 'O', 'VB'), ('the', 'O', 'DT'),
                     ('new', 'O', 'JJ'), ('combined', 'O', 'JJ'), ('group', 'O', 'NN'), ('-', 'O', ':'),
                     ('said', 'O', 'VBD'), ('he', 'O', 'PRP'), ('believed', 'O', 'VBD'), ('the', 'O', 'DT'),
                     ('two', 'NUMBER', 'CD'), ('supermarkets', 'O', 'NNS'), ('were', 'O', 'VBD'), ('"', 'O', '``'),
                     ('the', 'O', 'DT'), ('best', 'O', 'JJS'), ('possible', 'O', 'JJ'), ('fit', 'O', 'NN'),
                     ('"', 'O', "''"), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Walmart', 'ORGANIZATION', 'NNP'), (',', 'O', ','),
                     ('which', 'O', 'WDT'), ('has', 'O', 'VBZ'), ('owned', 'O', 'VBN'), ('Asda', 'ORGANIZATION', 'NNP'),
                     ('since', 'O', 'IN'), ('1999', 'DATE', 'CD'), (',', 'O', ','), ('will', 'O', 'MD'),
                     ('retain', 'O', 'VB'), ('42', 'PERCENT', 'CD'), ('%', 'PERCENT', 'NN'), ('of', 'O', 'IN'),
                     ('the', 'O', 'DT'), ('combined', 'O', 'JJ'), ('business', 'O', 'NN'), ('following', 'O', 'VBG'),
                     ('the', 'O', 'DT'), ('merger', 'O', 'NN'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('The', 'O', 'DT'), ('supermarkets', 'O', 'NNS'),
                     ('say', 'O', 'VBP'), ('that', 'O', 'IN'), ('as', 'O', 'IN'), ('a', 'O', 'DT'),
                     ('result', 'O', 'NN'), ('of', 'O', 'IN'), ('the', 'O', 'DT'), ('merger', 'O', 'NN'),
                     ('they', 'O', 'PRP'), ('expect', 'O', 'VBP'), ('to', 'O', 'TO'), ('be', 'O', 'VB'),
                     ('able', 'O', 'JJ'), ('to', 'O', 'TO'), ('lower', 'O', 'JJR'), ('prices', 'O', 'NNS'),
                     ('"', 'O', '``'), ('by', 'O', 'IN'), ('around', 'O', 'IN'), ('10', 'PERCENT', 'CD'),
                     ('%', 'PERCENT', 'NN'), ('on', 'O', 'IN'), ('many', 'O', 'JJ'), ('of', 'O', 'IN'),
                     ('the', 'O', 'DT'), ('products', 'O', 'NNS'), ('customers', 'O', 'NNS'), ('buy', 'O', 'VBP'),
                     ('regularly', 'O', 'RB'), ('"', 'O', "''"), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Sainsbury', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'),
                     ('and', 'O', 'CC'), ('Asda', 'ORGANIZATION', 'NNP'), ('will', 'O', 'MD'), ('remain', 'O', 'VB'),
                     ('separate', 'O', 'JJ'), ('brands', 'O', 'NNS'), ('and', 'O', 'CC'), ('no', 'O', 'DT'),
                     ('stores', 'O', 'NNS'), ('will', 'O', 'MD'), ('close', 'O', 'VB'), (',', 'O', ','),
                     ('Mr', 'O', 'NNP'), ('Coupe', 'PERSON', 'NNP'), ('told', 'O', 'VBD'), ('the', 'O', 'DT'),
                     ('BBC', 'ORGANIZATION', 'NNP'), ('.', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Media', 'O', 'NNP'), ('playback', 'O', 'NN'),
                     ('is', 'O', 'VBZ'), ('unsupported', 'O', 'JJ'), ('on', 'O', 'IN'), ('your', 'O', 'PRP$'),
                     ('device', 'O', 'NN'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Media', 'O', 'NNP'), ('captionSainsbury', 'O', 'NNP'),
                     ('\\', 'O', 'NNP'), ("'s", 'O', 'POS'), ('boss', 'TITLE', 'NN'), ('says', 'O', 'VBZ'),
                     ('the', 'O', 'DT'), ('merged', 'O', 'JJ'), ('firm', 'O', 'NN'), ('will', 'O', 'MD'),
                     ('"', 'O', '``'), ('invest', 'O', 'VB'), ('in', 'O', 'IN'), ('prices', 'O', 'NNS'),
                     ('"', 'O', "''"), ('"', 'O', '``'), ('There', 'O', 'EX'), ('\\', 'O', 'VBZ'), ("'s", 'O', 'POS'),
                     ('been', 'O', 'VBN'), ('a', 'O', 'DT'), ('bit', 'O', 'NN'), ('of', 'O', 'IN'),
                     ('commentary', 'O', 'NN'), ('over', 'O', 'IN'), ('the', 'DATE', 'DT'), ('weekend', 'DATE', 'NN'),
                     ('where', 'O', 'WRB'), ('people', 'O', 'NNS'), ('have', 'O', 'VBP'), ('been', 'O', 'VBN'),
                     ('alluding', 'O', 'VBG'), ('to', 'O', 'TO'), ('the', 'O', 'DT'), ('fact', 'O', 'NN'),
                     ('that', 'O', 'IN'), ('the', 'O', 'DT'), ('only', 'O', 'JJ'), ('way', 'O', 'NN'),
                     ('of', 'O', 'IN'), ('making', 'O', 'VBG'), ('this', 'O', 'DT'), ('happen', 'O', 'VB'),
                     ('is', 'O', 'VBZ'), ('by', 'O', 'IN'), ('closing', 'O', 'VBG'), ('stores', 'O', 'NNS'),
                     ('-', 'O', ':'), ('that', 'O', 'WDT'), ('is', 'O', 'VBZ'), ('not', 'O', 'RB'), ('true', 'O', 'JJ'),
                     (',', 'O', ','), ('"', 'O', "''"), ('said', 'O', 'VBD'), ('Mr', 'O', 'NNP'), ('Coupe', 'O', 'NNP'),
                     ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Following', 'O', 'VBG'), ('the', 'O', 'DT'),
                     ('merger', 'O', 'NN'), ('Argos', 'PERSON', 'NNS'), ('will', 'O', 'MD'), ('open', 'O', 'VB'),
                     ('outlets', 'O', 'NNS'), ('within', 'O', 'IN'), ('Asda', 'ORGANIZATION', 'NNP'),
                     ('stores', 'O', 'NNS'), (',', 'O', ','), ('the', 'O', 'DT'), ('firms', 'O', 'NNS'),
                     ('said', 'O', 'VBD'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Sainsbury', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'),
                     ('took', 'O', 'VBD'), ('over', 'O', 'RP'), ('Argos', 'ORGANIZATION', 'NNS'), ('in', 'O', 'IN'),
                     ('2016', 'DATE', 'CD'), ('and', 'O', 'CC'), ('has', 'O', 'VBZ'), ('been', 'O', 'VBN'),
                     ('integrating', 'O', 'VBG'), ('the', 'O', 'DT'), ('catalogue', 'O', 'NN'),
                     ('retailer', 'TITLE', 'NN'), ('into', 'O', 'IN'), ('its', 'O', 'PRP$'), ('own', 'O', 'JJ'),
                     ('stores', 'O', 'NNS'), ('.', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('The', 'O', 'DT'), ('combined', 'O', 'JJ'),
                     ('business', 'O', 'NN'), ('will', 'O', 'MD'), ('overtake', 'O', 'VB'), ('current', 'DATE', 'JJ'),
                     ('market', 'O', 'NN'), ('leader', 'TITLE', 'NN'), ('Tesco', 'ORGANIZATION', 'NNP'),
                     (',', 'O', ','), ('representing', 'O', 'VBG'), ('around', 'O', 'IN'), ('30', 'PERCENT', 'CD'),
                     ('%', 'PERCENT', 'NN'), ('of', 'O', 'IN'), ('UK', 'COUNTRY', 'NNP'), ('grocery', 'O', 'NN'),
                     ('sales', 'O', 'NNS'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('That', 'O', 'DT'), ('will', 'O', 'MD'), ('give', 'O', 'VB'),
                     ('it', 'O', 'PRP'), ('greater', 'O', 'JJR'), ('muscle', 'O', 'NN'), ('in', 'O', 'IN'),
                     ('the', 'O', 'DT'), ('market', 'O', 'NN'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Labour', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'),
                     ('shadow', 'O', 'NN'), ('business', 'TITLE', 'NN'), ('secretary', 'TITLE', 'NN'),
                     ('Rebecca', 'PERSON', 'NNP'), ('Long-Bailey', 'PERSON', 'NNP'), ('told', 'O', 'VBD'),
                     ('the', 'O', 'DT'), ('BBC', 'ORGANIZATION', 'NNP'), ('she', 'O', 'PRP'), ('was', 'O', 'VBD'),
                     ('concerned', 'O', 'VBN'), ('at', 'O', 'IN'), ('the', 'O', 'DT'), ('impact', 'O', 'NN'),
                     ('on', 'O', 'IN'), ('suppliers', 'O', 'NNS'), ('of', 'O', 'IN'), ('the', 'O', 'DT'),
                     ('proposed', 'O', 'VBN'), ('tie-up', 'O', 'NN'), ('.', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('The', 'O', 'DT'), ('combined', 'O', 'JJ'),
                     ('group', 'O', 'NN'), ('"', 'O', '``'), ('will', 'O', 'MD'), ('have', 'O', 'VB'),
                     ('immense', 'O', 'JJ'), ('purchasing', 'O', 'VBG'), ('power', 'O', 'NN'), (',', 'O', ','),
                     ('giving', 'O', 'VBG'), ('them', 'O', 'PRP'), ('an', 'O', 'DT'), ('opportunity', 'O', 'NN'),
                     ('to', 'O', 'TO'), ('bargain', 'O', 'NN'), ('very', 'O', 'RB'), ('hard', 'O', 'RB'),
                     ('with', 'O', 'IN'), ('suppliers', 'O', 'NNS'), (',', 'O', ','), ('"', 'O', "''"),
                     ('she', 'O', 'PRP'), ('warned', 'O', 'VBD'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Mike', 'PERSON', 'NNP'), ('Cherry', 'PERSON', 'NNP'),
                     (',', 'O', ','), ('national', 'O', 'JJ'), ('chairman', 'TITLE', 'NN'), ('of', 'O', 'IN'),
                     ('the', 'O', 'DT'), ('Federation', 'ORGANIZATION', 'NNP'), ('of', 'ORGANIZATION', 'IN'),
                     ('Small', 'ORGANIZATION', 'JJ'), ('Businesses', 'ORGANIZATION', 'NNS'), (',', 'O', ','),
                     ('said', 'O', 'VBD'), ('the', 'O', 'DT'), ('firms', 'O', 'NNS'), ('should', 'O', 'MD'),
                     ('explain', 'O', 'VB'), ('how', 'O', 'WRB'), ('they', 'O', 'PRP'), ('plan', 'O', 'VBP'),
                     ('to', 'O', 'TO'), ('merge', 'O', 'VB'), ('their', 'O', 'PRP$'), ('supply', 'O', 'NN'),
                     ('chains', 'O', 'NNS'), ('fairly', 'O', 'RB'), (',', 'O', ','), ('and', 'O', 'CC'),
                     ('reassure', 'O', 'VB'), ('people', 'O', 'NNS'), ('that', 'O', 'WDT'), ('cost', 'O', 'VBP'),
                     ('savings', 'O', 'NNS'), ('wouldn', 'O', 'JJ'), ('\\', 'O', 'NN'), ("'", 'O', "''"),
                     ('t', 'O', 'NN'), ('be', 'O', 'VB'), ('achieved', 'O', 'VBN'), ('"', 'O', '``'),
                     ('simply', 'O', 'RB'), ('by', 'O', 'IN'), ('milking', 'O', 'VBG'), ('their', 'O', 'PRP$'),
                     ('small', 'O', 'JJ'), ('suppliers', 'O', 'NNS'), ('for', 'O', 'IN'), ('all', 'O', 'DT'),
                     ('they', 'O', 'PRP'), ('\\', 'O', 'VBP'), ("'re", 'O', 'VBP'), ('worth', 'O', 'JJ'),
                     ('"', 'O', "''"), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Sainsbury', 'ORGANIZATION', 'NNP'), ('\\', 'O', 'NNP'),
                     ("'s", 'O', 'POS'), ('and', 'O', 'CC'), ('Asda', 'ORGANIZATION', 'NNP'),
                     ('executives', 'O', 'NNS'), ('said', 'O', 'VBD'), ('one', 'NUMBER', 'CD'),
                     ('advantage', 'O', 'NN'), ('of', 'O', 'IN'), ('the', 'O', 'DT'), ('merger', 'O', 'NN'),
                     ('would', 'O', 'MD'), ('be', 'O', 'VB'), ('the', 'O', 'DT'), ('opportunity', 'O', 'NN'),
                     ('to', 'O', 'TO'), ('bring', 'O', 'VB'), ('in', 'O', 'RP'), ('"', 'O', '``'), ('the', 'O', 'DT'),
                     ('power', 'O', 'NN'), ('of', 'O', 'IN'), ('Walmart', 'ORGANIZATION', 'NNP'), ('in', 'O', 'IN'),
                     ('the', 'O', 'DT'), ('form', 'O', 'NN'), ('of', 'O', 'IN'), ('buying', 'O', 'NN'),
                     ('of', 'O', 'IN'), ('general', 'TITLE', 'JJ'), ('merchandise', 'O', 'NN'), ('and', 'O', 'CC'),
                     ('in', 'O', 'IN'), ('the', 'O', 'DT'), ('form', 'O', 'NN'), ('of', 'O', 'IN'),
                     ('their', 'O', 'PRP$'), ('systems', 'O', 'NNS'), ('and', 'O', 'CC'), ('investments', 'O', 'NNS'),
                     ('"', 'O', "''"), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Sainsbury', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'),
                     ('and', 'O', 'CC'), ('Asda', 'ORGANIZATION', 'NNP'), ('have', 'O', 'VBP'), ('asked', 'O', 'VBN'),
                     ('for', 'O', 'IN'), ('the', 'O', 'DT'), ('CMA', 'ORGANIZATION', 'NNP'),
                     ('investigation', 'O', 'NN'), ('to', 'O', 'TO'), ('be', 'O', 'VB'), ('fast-tracked', 'O', 'JJ'),
                     ('and', 'O', 'CC'), ('hope', 'O', 'VBP'), ('to', 'O', 'TO'), ('complete', 'O', 'VB'),
                     ('the', 'O', 'DT'), ('deal', 'O', 'NN'), ('by', 'O', 'IN'), ('the', 'DATE', 'DT'),
                     ('autumn', 'DATE', 'NN'), ('of', 'DATE', 'IN'), ('2019', 'DATE', 'CD'), ('.', 'O', '.'),
                     ('"', 'O', "''")], [('b', 'O', 'NN'), ("'", 'O', '``'), ('At', 'O', 'IN'), ('the', 'DATE', 'DT'),
                                         ('weekend', 'DATE', 'NN'), (',', 'O', ','), ('Liberal', 'IDEOLOGY', 'NNP'),
                                         ('Democrat', 'IDEOLOGY', 'NNP'), ('leader', 'TITLE', 'NN'),
                                         ('Sir', 'O', 'NNP'), ('Vince', 'PERSON', 'NNP'), ('Cable', 'PERSON', 'NNP'),
                                         ('said', 'O', 'VBD'), ('the', 'O', 'DT'), ('merger', 'O', 'NN'),
                                         ('risked', 'O', 'VBD'), ('creating', 'O', 'VBG'), ('"', 'O', '``'),
                                         ('even', 'O', 'RB'), ('more', 'O', 'RBR'), ('concentrated', 'O', 'JJ'),
                                         ('local', 'O', 'JJ'), ('monopolies', 'O', 'NNS'), ('"', 'O', "''"),
                                         ('and', 'O', 'CC'), ('said', 'O', 'VBD'), ('the', 'O', 'DT'),
                                         ('CMA', 'ORGANIZATION', 'NNP'), ('should', 'O', 'MD'), ('force', 'O', 'VB'),
                                         ('the', 'O', 'DT'), ('companies', 'O', 'NNS'), ('to', 'O', 'TO'),
                                         ('sell', 'O', 'VB'), ('off', 'O', 'RP'), ('stores', 'O', 'NNS'),
                                         ('if', 'O', 'IN'), ('the', 'O', 'DT'), ('new', 'O', 'JJ'),
                                         ('giant', 'O', 'NN'), ('was', 'O', 'VBD'), ('dominant', 'O', 'JJ'),
                                         ('in', 'O', 'IN'), ('a', 'O', 'DT'), ('particular', 'O', 'JJ'),
                                         ('area', 'O', 'NN'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Retail', 'O', 'NNP'), ('analyst', 'TITLE', 'NN'),
                     ('Nick', 'PERSON', 'NNP'), ('Bubb', 'PERSON', 'NNP'), ('said', 'O', 'VBD'), ('he', 'O', 'PRP'),
                     ('thought', 'O', 'VBD'), ('there', 'O', 'EX'), ('was', 'O', 'VBD'), ('"', 'O', '``'),
                     ('a', 'O', 'DT'), ('pretty', 'O', 'RB'), ('good', 'O', 'JJ'), ('chance', 'O', 'NN'),
                     ('"', 'O', "''"), ('that', 'O', 'IN'), ('the', 'O', 'DT'), ('deal', 'O', 'NN'),
                     ('will', 'O', 'MD'), ('be', 'O', 'VB'), ('allowed', 'O', 'VBN'), ('to', 'O', 'TO'),
                     ('proceed', 'O', 'VB'), (',', 'O', ','), ('but', 'O', 'CC'), ('the', 'O', 'DT'),
                     ('main', 'O', 'JJ'), ('debate', 'O', 'NN'), ('would', 'O', 'MD'), ('be', 'O', 'VB'),
                     ('over', 'O', 'IN'), ('how', 'O', 'WRB'), ('many', 'O', 'JJ'), ('stores', 'O', 'NNS'),
                     ('Sainsbury', 'O', 'NNP'), ('\\', 'O', 'NNP'), ("'s", 'O', 'POS'), ('and', 'O', 'CC'),
                     ('Asda', 'ORGANIZATION', 'NNP'), ('would', 'O', 'MD'), ('have', 'O', 'VB'), ('to', 'O', 'TO'),
                     ('sell', 'O', 'VB'), ('"', 'O', '``'), ('to', 'O', 'TO'), ('placate', 'O', 'VB'),
                     ('the', 'O', 'DT'), ('CMA', 'ORGANIZATION', 'NNP'), ('"', 'O', "''"), ('.', 'O', '.'),
                     ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', "''"), ('"', 'O', '``'), ('Too', 'O', 'RB'), ('many', 'O', 'JJ'),
                     ('store', 'O', 'NN'), ('disposals', 'O', 'NNS'), ('and', 'O', 'CC'), ('the', 'O', 'DT'),
                     ('deal', 'O', 'NN'), ('won', 'O', 'VBD'), ('\\', 'O', 'NN'), ("'", 'O', "''"), ('t', 'O', 'NN'),
                     ('be', 'O', 'VB'), ('worth', 'O', 'JJ'), ('doing', 'O', 'VBG'), ('...', 'O', ':'),
                     ('too', 'O', 'RB'), ('few', 'O', 'JJ'), ('store', 'O', 'NN'), ('disposals', 'O', 'NNS'),
                     ('and', 'O', 'CC'), ('the', 'O', 'DT'), ('CMA', 'ORGANIZATION', 'NNP'), ('will', 'O', 'MD'),
                     ('look', 'O', 'VB'), ('toothless', 'O', 'JJ'), ('hopefully', 'O', 'RB'), ('there', 'O', 'EX'),
                     ('will', 'O', 'MD'), ('be', 'O', 'VB'), ('a', 'O', 'DT'), ('"', 'O', '``'),
                     ('Goldilocks', 'O', 'NNP'), ('"', 'O', "''"), ('scenario', 'O', 'NN'), ('for', 'O', 'IN'),
                     ('Sainsbury', 'ORGANIZATION', 'NNP'), ('\\', 'O', 'NNP'), ("'s", 'O', 'POS'), ('/', 'O', ':'),
                     ('Asda', 'ORGANIZATION', 'NNP'), ('.', 'O', '.'), ('"', 'O', "''"), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Sainsbury', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'),
                     ('and', 'O', 'CC'), ('Asda', 'ORGANIZATION', 'NNP'), ('are', 'O', 'VBP'), ('both', 'O', 'DT'),
                     ('being', 'O', 'VBG'), ('buffeted', 'O', 'VBN'), ('by', 'O', 'IN'), ('competition', 'O', 'NN'),
                     ('from', 'O', 'IN'), ('budget', 'O', 'NN'), ('supermarkets', 'O', 'NNS'), ('such', 'O', 'JJ'),
                     ('as', 'O', 'IN'), ('Aldi', 'ORGANIZATION', 'NNP'), ('and', 'O', 'CC'),
                     ('Lidl', 'ORGANIZATION', 'NNP'), ('.', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('On', 'O', 'IN'), ('the', 'O', 'DT'), ('horizon', 'O', 'NN'),
                     (',', 'O', ','), ('Amazon', 'LOCATION', 'NNP'), ('is', 'O', 'VBZ'), ('making', 'O', 'VBG'),
                     ('initial', 'O', 'JJ'), ('steps', 'O', 'NNS'), ('into', 'O', 'IN'), ('grocery', 'O', 'NN'),
                     ('deliveries', 'O', 'NNS'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', "''"), ('"', 'O', '``'), ('I', 'O', 'PRP'), ('think', 'O', 'VBP'),
                     ('from', 'O', 'IN'), ('a', 'O', 'DT'), ('market', 'O', 'NN'), ('share', 'O', 'NN'),
                     ('perspective', 'O', 'NN'), (',', 'O', ','), ('both', 'O', 'CC'),
                     ('Sainsbury', 'ORGANIZATION', 'NNP'), ('\\', 'O', 'NNP'), ("'s", 'O', 'POS'), ('and', 'O', 'CC'),
                     ('Asda', 'ORGANIZATION', 'NNP'), ('are', 'O', 'VBP'), ('landlocked', 'O', 'JJ'), ('to', 'O', 'TO'),
                     ('a', 'O', 'DT'), ('certain', 'O', 'JJ'), ('extent', 'O', 'NN'), ('.', 'O', '.'),
                     ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('They', 'O', 'PRP'), ('\\', 'O', 'VBP'), ("'re", 'O', 'VBP'),
                     ('not', 'O', 'RB'), ('really', 'O', 'RB'), ('able', 'O', 'JJ'), ('to', 'O', 'TO'),
                     ('grow', 'O', 'VB'), ('at', 'O', 'IN'), ('a', 'O', 'DT'), ('rapid', 'O', 'JJ'),
                     ('rate', 'O', 'NN'), (',', 'O', ','), ('"', 'O', "''"), ('said', 'O', 'VBD'),
                     ('Steve', 'PERSON', 'NNP'), ('Dresser', 'PERSON', 'NNP'), (',', 'O', ','),
                     ('director', 'TITLE', 'NN'), ('of', 'O', 'IN'), ('the', 'O', 'DT'), ('Retail', 'O', 'NNP'),
                     ('Insight', 'O', 'NNP'), ('consultancy', 'O', 'NN'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Image', 'O', 'NN'), ('copyrightAFPThe', 'O', 'NN'),
                     ('two', 'NUMBER', 'CD'), ('chains', 'O', 'NNS'), ('are', 'O', 'VBP'), ('in', 'O', 'IN'),
                     ('many', 'O', 'JJ'), ('ways', 'O', 'NNS'), ('complementary', 'O', 'JJ'), (':', 'O', ':'),
                     ('Sainsbury', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'), ('stores', 'O', 'NNS'),
                     ('are', 'O', 'VBP'), ('focused', 'O', 'VBN'), ('more', 'O', 'RBR'), ('in', 'O', 'IN'),
                     ('the', 'O', 'DT'), ('south', 'O', 'NN'), ('of', 'O', 'IN'), ('the', 'O', 'DT'),
                     ('UK', 'COUNTRY', 'NNP'), ('and', 'O', 'CC'), ('target', 'O', 'VB'), ('a', 'O', 'DT'),
                     ('higher-end', 'O', 'JJ'), ('market', 'O', 'NN'), ('segment', 'O', 'NN'), ('.', 'O', '.'),
                     ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Asda', 'ORGANIZATION', 'NNP'), ('is', 'O', 'VBZ'),
                     ('more', 'O', 'RBR'), ('concentrated', 'O', 'JJ'), ('in', 'O', 'IN'), ('the', 'O', 'DT'),
                     ('north', 'O', 'NN'), (',', 'O', ','), ('offering', 'O', 'VBG'), ('lower-cost', 'O', 'JJ'),
                     ('groceries', 'O', 'NNS'), ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', "''"), ('"', 'O', '``'), ('If', 'O', 'IN'), ('they', 'O', 'PRP'),
                     ('remain', 'O', 'VBP'), ('on', 'O', 'IN'), ('their', 'O', 'PRP$'), ('own', 'O', 'JJ'),
                     ('it', 'O', 'PRP'), ('\\', 'O', 'NN'), ("'s", 'O', 'POS'), ('difficult', 'O', 'JJ'),
                     ('to', 'O', 'TO'), ('see', 'O', 'VB'), ('how', 'O', 'WRB'), ('they', 'O', 'PRP'),
                     ('get', 'O', 'VBP'), ('any', 'O', 'DT'), ('real', 'O', 'JJ'), ('growth', 'O', 'NN'),
                     ('beyond', 'O', 'IN'), ('standard', 'O', 'JJ'), ('organic', 'O', 'JJ'), ('growth', 'O', 'NN'),
                     (',', 'O', ','), ('which', 'O', 'WDT'), ('isn', 'O', 'VBP'), ('\\', 'O', 'NN'), ("'", 'O', "''"),
                     ('t', 'O', 'NN'), ('necessarily', 'O', 'RB'), ('going', 'O', 'VBG'), ('to', 'O', 'TO'),
                     ('be', 'O', 'VB'), ('enough', 'O', 'RB'), ('when', 'O', 'WRB'), ('Amazon', 'LOCATION', 'NNP'),
                     ('joins', 'O', 'VBZ'), ('the', 'O', 'DT'), ('market', 'O', 'NN'), (',', 'O', ','),
                     ('"', 'O', "''"), ('said', 'O', 'VBD'), ('Mr', 'O', 'NNP'), ('Dresser', 'PERSON', 'NNP'),
                     ('.', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ('"', 'O', '``'), ('Will', 'O', 'MD'), ('the', 'O', 'DT'),
                     ('Sainsbury', 'ORGANIZATION', 'NNP'), ("'s", 'O', 'POS'), ('and', 'O', 'CC'),
                     ('Asda', 'ORGANIZATION', 'NNP'), ('merger', 'O', 'NN'), ('affect', 'O', 'VB'), ('you', 'O', 'PRP'),
                     ('?', 'O', '.'), ('"', 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('What', 'O', 'WP'), ('do', 'O', 'VBP'), ('you', 'O', 'PRP'),
                     ('want', 'O', 'VB'), ('to', 'O', 'TO'), ('know', 'O', 'VB'), ('about', 'O', 'IN'),
                     ('it', 'O', 'PRP'), ('?', 'O', '.'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('Use', 'O', 'VB'), ('this', 'O', 'DT'), ('form', 'O', 'NN'),
                     ('to', 'O', 'TO'), ('ask', 'O', 'VB'), ('your', 'O', 'PRP$'), ('question', 'O', 'NN'),
                     (':', 'O', ':'), ("'", 'O', "''")],
                    [('b', 'O', 'NN'), ("'", 'O', '``'), ('If', 'O', 'IN'), ('you', 'O', 'PRP'), ('are', 'O', 'VBP'),
                     ('reading', 'O', 'VBG'), ('this', 'O', 'DT'), ('page', 'O', 'NN'), ('on', 'O', 'IN'),
                     ('the', 'O', 'DT'), ('BBC', 'ORGANIZATION', 'NNP'), ('News', 'ORGANIZATION', 'NNP'),
                     ('app', 'O', 'NN'), (',', 'O', ','), ('you', 'O', 'PRP'), ('will', 'O', 'MD'), ('need', 'O', 'VB'),
                     ('to', 'O', 'TO'), ('visit', 'O', 'VB'), ('the', 'O', 'DT'), ('mobile', 'TITLE', 'JJ'),
                     ('version', 'O', 'NN'), ('of', 'O', 'IN'), ('the', 'O', 'DT'), ('BBC', 'ORGANIZATION', 'NNP'),
                     ('website', 'O', 'NN'), ('to', 'O', 'TO'), ('submit', 'O', 'VB'), ('your', 'O', 'PRP$'),
                     ('question', 'O', 'NN'), ('on', 'O', 'IN'), ('this', 'O', 'DT'), ('topic', 'O', 'NN'),
                     ('.', 'O', '.'), ("'", 'O', "''")]]
NER_tags = {'O': [
    'she was concerned at the impact on suppliers of the proposed tie-up . " b \' The combined group " will have immense purchasing power , giving them an opportunity to bargain very hard with suppliers , " she warned . \' b \'',
    'is more concentrated in the north , offering lower-cost groceries . \' b \' " If they remain on their own it \\ \'s difficult to see how they get any real growth beyond standard organic growth , which isn \\ \' t necessarily going to be enough when',
    'owned by', ', representing around',
    'also said the deal would not lead to store closures or job losses in stores . " b " The combination of the',
    'largest supermarkets would create a giant , representing nearly', '. " b \' At',
    'spent on groceries . " b \' Mr Coupe - who will lead the new combined group - said he believed the', 'of',
    ', which has owned', 'app , you will need to visit the', ', national', '. " b \' On the horizon ,',
    'joins the market , " said Mr', 'advantage of the merger would be the opportunity to bring in " the power of', ',',
    'grocery sales . \' b \' That will give it greater muscle in the market . \' b "',
    'merger affect you ? " b \' What do you want to know about it ? \' b \' Use this form to ask your question : \' b \' If you are reading this page on the',
    "'s", 'have asked for the', 'in the form of buying of', 'will remain separate brands and no stores will close , Mr',
    'said he thought there was " a pretty good chance " that the deal will be allowed to proceed , but the main debate would be over how many stores Sainsbury \\ \'s and',
    'are both being buffeted by competition from budget supermarkets such as',
    'and target a higher-end market segment . " b \'', 'market', 'supermarket giant',
    'said the merger risked creating " even more concentrated local monopolies " and said the', "\\ 's /",
    'supermarkets were " the best possible fit " . \' b \'',
    'says the merged firm will " invest in prices " " There \\ \'s been a bit of commentary over', 'Sir', "'s shadow",
    'of the', '. \' b " Will the',
    'is making initial steps into grocery deliveries . \' b \' " I think from a market share perspective , both',
    'since', "'s and", 'and', 'told the',
    'are landlocked to a certain extent . \' b \' They \\ \'re not really able to grow at a rapid rate , " said',
    '. " b \' Media playback is unsupported on your device \' b \' Media captionSainsbury \\ \'s',
    'stores , the firms said . \' b "', 'in every',
    'where people have been alluding to the fact that the only way of making this happen is by closing stores - that is not true , " said Mr Coupe . \' b \' Following the merger',
    'and has been integrating the catalogue',
    'b " Image copyrightGetty ImagesSainsbury \'s has confirmed plans to merge with', "'s took over",
    'investigation to be fast-tracked and hope to complete the deal by',
    'of the Retail Insight consultancy . \' b " Image copyrightAFPThe', 'executives said',
    "should force the companies to sell off stores if the new giant was dominant in a particular area . ' b ' Retail",
    'version of the', 'would have to sell " to placate the',
    '" . \' b \' " Too many store disposals and the deal won \\ \' t be worth doing ... too few store disposals and the',
    '. " b "', 'chains are in many ways complementary :', "\\ 's and",
    'merchandise and in the form of their systems and investments " . \' b "', ', will retain',
    'of the combined business following the merger . \' b \' The supermarkets say that as a result of the merger they expect to be able to lower prices " by around',
    'in', ', which is', 'on many of the products customers buy regularly " . \' b "',
    ', said the firms should explain how they plan to merge their supply chains fairly , and reassure people that cost savings wouldn \\ \' t be achieved " simply by milking their small suppliers for all they \\ \'re worth " . \' b \'',
    'will open outlets within', 'will look toothless hopefully there will be a " Goldilocks " scenario for',
    "website to submit your question on this topic . '", "'s stores are focused more in the south of the",
    'into its own stores . " b \' The combined business will overtake', '. " \' b "'],
    'ORGANIZATION': ['Asda', 'Sainsbury', 'CMA', 'Walmart', 'Lidl', 'BBC', 'Aldi', 'Labour',
                     'Federation of Small Businesses', 'Tesco', 'Argos', 'BBC News'],
    'DATE': ['currently', 'current', '1999', 'the weekend', 'the autumn of 2019', '2016'],
    'COUNTRY': ['UK', 'US'],
    'TITLE': ['director', 'general', 'chairman', 'leader', 'analyst', 'retailer', 'chief executive', 'mobile',
              'boss', 'business secretary'],
    'PERSON': ['Steve Dresser', 'Mike Coupe', 'Mike Cherry', 'Dresser', 'Coupe', 'Vince Cable',
               'Rebecca Long-Bailey', 'Argos', 'Nick Bubb'], 'ORDINAL': ['second and third'],
    'NUMBER': ['1', '3', 'one', 'two'], 'PERCENT': ['42 %', '10 %', '30 %'], 'IDEOLOGY': ['Liberal Democrat'],
    'LOCATION': ['Amazon']}

NER_tags_to_append = {'O': [
    'she was concerned at the impact on suppliers of the proposed tie-up . " b \' The combined group " will have immense purchasing power , giving them an opportunity to bargain very hard with suppliers , " she warned . \' b \'',
    'is more concentrated in the north , offering lower-cost groceries . \' b \' " If they remain on their own it \\ \'s difficult to see how they get any real growth beyond standard organic growth , which isn \\ \' t necessarily going to be enough when',
    'owned by', ', representing around',
    'also said the deal would not lead to store closures or job losses in stores . " b " The combination of the',
    'largest supermarkets would create a giant , representing nearly', '. " b \' At',
    'spent on groceries . " b \' Mr Coupe - who will lead the new combined group - said he believed the', 'of',
    ', which has owned', 'app , you will need to visit the', ', national', '. " b \' On the horizon ,',
    'joins the market , " said Mr', 'advantage of the merger would be the opportunity to bring in " the power of', ',',
    'grocery sales . \' b \' That will give it greater muscle in the market . \' b "',
    'merger affect you ? " b \' What do you want to know about it ? \' b \' Use this form to ask your question : \' b \' If you are reading this page on the',
    "'s", 'have asked for the', 'in the form of buying of', 'will remain separate brands and no stores will close , Mr',
    'said he thought there was " a pretty good chance " that the deal will be allowed to proceed , but the main debate would be over how many stores Sainsbury \\ \'s and',
    'are both being buffeted by competition from budget supermarkets such as',
    'and target a higher-end market segment . " b \'', 'market', 'supermarket giant',
    'said the merger risked creating " even more concentrated local monopolies " and said the', "\\ 's /",
    'supermarkets were " the best possible fit " . \' b \'',
    'says the merged firm will " invest in prices " " There \\ \'s been a bit of commentary over', 'Sir', "'s shadow",
    'of the', '. \' b " Will the',
    'is making initial steps into grocery deliveries . \' b \' " I think from a market share perspective , both',
    'since', "'s and", 'and', 'told the',
    'are landlocked to a certain extent . \' b \' They \\ \'re not really able to grow at a rapid rate , " said',
    '. " b \' Media playback is unsupported on your device \' b \' Media captionSainsbury \\ \'s',
    'stores , the firms said . \' b "', 'in every',
    'where people have been alluding to the fact that the only way of making this happen is by closing stores - that is not true , " said Mr Coupe . \' b \' Following the merger',
    'and has been integrating the catalogue',
    'b " Image copyrightGetty ImagesSainsbury \'s has confirmed plans to merge with', "'s took over",
    'investigation to be fast-tracked and hope to complete the deal by',
    'of the Retail Insight consultancy . \' b " Image copyrightAFPThe', 'executives said',
    "should force the companies to sell off stores if the new giant was dominant in a particular area . ' b ' Retail",
    'version of the', 'would have to sell " to placate the',
    '" . \' b \' " Too many store disposals and the deal won \\ \' t be worth doing ... too few store disposals and the',
    '. " b "', 'chains are in many ways complementary :', "\\ 's and",
    'merchandise and in the form of their systems and investments " . \' b "', ', will retain',
    'of the combined business following the merger . \' b \' The supermarkets say that as a result of the merger they expect to be able to lower prices " by around',
    'in', ', which is', 'on many of the products customers buy regularly " . \' b "',
    ', said the firms should explain how they plan to merge their supply chains fairly , and reassure people that cost savings wouldn \\ \' t be achieved " simply by milking their small suppliers for all they \\ \'re worth " . \' b \'',
    'will open outlets within', 'will look toothless hopefully there will be a " Goldilocks " scenario for',
    "website to submit your question on this topic . '", "'s stores are focused more in the south of the",
    'into its own stores . " b \' The combined business will overtake', '. " \' b "'],
    'ORGANIZATION': ['Asda', 'Sainsbury', 'CMA', 'Walmart', 'Lidl', 'BBC', 'Aldi', 'Labour',
                     'Federation of Small Businesses', 'Tesco', 'Argos', 'BBC News'],
    'DATE': ['currently', 'current', '1999', 'the weekend', 'the autumn of 2019', '2016'],
    'COUNTRY': ['UK', 'US'],
    'TITLE': ['director', 'general', 'chairman', 'leader', 'analyst', 'retailer', 'chief executive',
              'mobile', 'boss', 'business secretary'],
    'PERSON': ['Steve Dresser', 'Mike Coupe', 'Mike Cherry', 'Dresser', 'Coupe', 'Vince Cable',
               'Rebecca Long-Bailey', 'Argos', 'Nick Bubb'],
    'ORDINAL': ['second and third', 'second and third', 'second and third'],
    'NUMBER': ['1', '3', 'one', 'two'], 'PERCENT': ['42 %', '10 %', '30 %'],
    'IDEOLOGY': ['Liberal Democrat', 'Liberal Democrat', 'Liberal Democrat'],
    'LOCATION': ['Amazon', 'Amazon', 'Amazon', 'Amazon']}

import random


def build_subject_from_NER_tag_and_tagged_sentence(NER_tags, tagged_sentences, NER_tags_to_append):
    subjects_complete_list = []
    sentences_to_use = tagged_sentences
    # for i in range(1, 5):
    #     chosen_sentence = random.choice(tagged_sentences)
    #     tagged_sentences.remove(chosen_sentence)
    #     sentences_to_use.append(chosen_sentence)

    for current_sentence in sentences_to_use:
        for i in range(2, current_sentence.__len__()):
            this_NER_tag = current_sentence[i][1]
            if this_NER_tag is not 'O':
                this_tagged_word = current_sentence[i][0]
                m = i + 1
                while current_sentence[m][1] is this_NER_tag:
                    this_tagged_word += ' ' + current_sentence[m][0]
                    m += 1
                choices_complete_list = NER_tags[this_NER_tag].copy()
                if choices_complete_list.__len__() < 4:
                    for x in NER_tags_to_append[this_NER_tag]:
                        choices_complete_list.append(x)
                try:
                    choice_A = this_tagged_word
                    choices_complete_list.remove(choice_A)
                    choice_B = random.choice(choices_complete_list)
                    choices_complete_list.remove(choice_B)
                    choice_C = random.choice(choices_complete_list)
                    choices_complete_list.remove(choice_C)
                    choice_D = random.choice(choices_complete_list)
                    choices_complete_list.remove(choice_D)
                except:
                    break
                    # raise Exception('NER tags is not enough!')
                question = ''
                for cursor in range(2, current_sentence.__len__()):
                    cursor_tagged_word = current_sentence[cursor][0]
                    cursor_tag = current_sentence[cursor][1]
                    next_cursor = cursor + 1
                    if next_cursor >= current_sentence.__len__():
                        continue
                    while current_sentence[next_cursor][1] is cursor_tag and cursor_tag is not 'O':
                        cursor_tagged_word += ' ' + current_sentence[next_cursor][0]
                        next_cursor += 1
                    if cursor_tagged_word is not this_tagged_word:
                        question += cursor_tagged_word + ' '
                    elif cursor_tagged_word is this_tagged_word:
                        question += '_______' + ' '

                subject = {
                    'question': question,
                    'choices': [choice_A, choice_B, choice_C, choice_D],
                    'answer': 'A'
                }

                subjects_complete_list.append(subject)
                break

    return subjects_complete_list


su = build_subject_from_NER_tag_and_tagged_sentence(NER_tags, tagged_sentences, NER_tags_to_append)
